### ISSUE TITLE
benchmark tools support metrics for Docker deployment

### ISSUE THREAD

**Issue by xiguiw** [opea-project/GenAIEval#100]
Benchmark tools support metrics for Kubernetes, there is no metrics for docker.

Requirment:
1. Need to support metrics for Docker deployment.
2. Dump system HW information and configuration of the workload.

**Comment by gavinlichn** [comment]
@bjzhjing will work on this

**Comment by gavinlichn** [comment]
PR for docker metrics: https://github.com/opea-project/GenAIEval/pull/113

**Comment by joshuayao** [comment]
Hi @xiguiw, can I close this issue?

**Comment by xiguiw** [comment]
Close as it is done!

Thanks @gavinlichn @bjzhjing  !
